### ISSUE TITLE
Application hangs with empty-ish GUI

### ISSUE THREAD

**Issue by cdaringe** [SolderedElectronics/Soldered-Image-Converter#2]
# Problem Statement

While trying to figure out precisely how to format grayscale binary bitmap data,  I checked if this project has references, but the application was not interactable. The format is not documented [here in the docs](https://inkplate.readthedocs.io/en/latest/arduino.html#inkplate-drawbitmap3bit) where I expected--it just said "see the examples". I wasn't sure what examples, and assumed it maybe meant this repo?

On load of an image into the application, the app renders all of the controls empty/white:

![image](https://github.com/user-attachments/assets/5e63fada-037a-416b-8d36-d00ccf17af7f)

**Comment by rsoric** [comment]
Hi @cdaringe 

Sorry to hear that this was the case, we've built and tested the application on Windows thus far, you're running it on mac right? This obviously shouldn't happen, to me it looks like it's displaying no fonts or text whatsoever, so that it something I'll have to look into compatibility with in PySide6 which is the library I'm using for GUI.

You can maybe still save the .h file by clicking save header file in the app. It's worth trying. 

I believe the docs are talking about the Inkplate library's Arduino examples, (for example, [this](https://github.com/SolderedElectronics/Inkplate-Arduino-library/blob/master/examples/Inkplate6/Basic/Inkplate6_Grayscale/image.h)).

But, to still help out I'll explain Inkplate's grayscale data format. 
Pixels go from the upper left corner to the right, row by row and are stored in uint8_t bytes. In a byte, you have two pixels eg. 0x000x111x. That would be a totally black pixel next to a totally white pixel, and values are grayscale'd in the same way, counting from 000 as darkest to 111 as lightest. As you can see there's two extra bits that do not matter, those being the fourth and the eight.

Hope that helps. I've also made a request to update Inkplate's docs to be more informative regarding the Image data format.

I'll have to leave this issue open until a compatibility fix for mac is found. In the meantime, could you try using the [older ](https://solderedelectronics.github.io/Inkplate-image-converter/) image converter which we still have up?

-Rob

**Comment by cdaringe** [comment]
> you're running it on mac right?

correct!

> But, to still help out I'll explain Inkplate's grayscale data format.

thank you for this! very helpful. i was able to progress :)

**Comment by rsoric** [comment]
Hi @cdaringe 

It just occurred to me - could you install Source Sans Pro? I believe that's the font I'm using for the GUI here. It should be a free font, I found [this](https://www.fontsquirrel.com/fonts/source-sans-pro). Try running the app again then.

We are also looking into making and testing builds for Mac and Linux so that this doesn't happen.

-Rob

**Comment by cdaringe** [comment]
Splendid idea! But no worries—i had moved on successfully by that point! Im afk for a week. Probably fine to even close the github issue unless you all want to keep it open for tracking purposes! Much appreciated!

**Comment by rsoric** [comment]
No problem, I'll be working on an update to create and test builds for mac and linux, I'll report back and close the issue when we have that going :)

**Comment by rsoric** [comment]
Hey @cdaringe , I've made a [push to the dev branch](https://github.com/SolderedElectronics/Soldered-Image-Converter/tree/cdf7b00962896656f5a8a078c2f35176052a7545) with the font styles fixed. It has worked on a colleague's PC where the font wasn't displaying correctly previously. 

Also some other Inkplate boards (which support 3-bit grayscale) were also added in this update.

Could you please download the code in that commit I linked, try to run it and verify if this fixed the issue?

**Comment by rsoric** [comment]
Hey @cdaringe, this was solved in a [recent push to dev](https://github.com/SolderedElectronics/Soldered-Image-Converter/commit/67a717b7298f2a75a8354c3915d9b0299db1bda1), tested on my colleague @BornaBiro's very own mac. The fonts now display fine. However, there are still issues with the dropdown menus but we're working on it.

Thanks for pointing it out!
